"""Block 2: Lighthouse, mobile + desktop, 3 runs per page, median.

Conditions: Lighthouse 12 default throttling (mobile: Moto G Power emulation,
simulated slow 4G 150 ms RTT / 1.6 Mbps, 4x CPU slowdown; desktop: 1350x940,
40 ms RTT / 10 Mbps, no CPU slowdown) on a Pentium G4560 headless server,
Chromium from Playwright. Absolute numbers are pessimistic vs. real devices.

Output: data/lighthouse.json (medians + every run), raw reports in
data/lighthouse/raw/ (gitignored, regenerated by the script).
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from common import AUDIT_DIR, CHROME, DATA_DIR, KEY_PAGES, median, save_json, url  # noqa: E402

RUNS = int(os.environ.get("LH_RUNS", "3"))
LH = AUDIT_DIR / "node_modules/.bin/lighthouse"
RAW = DATA_DIR / "lighthouse" / "raw"

# The Russian audience may land on the GitHub Pages copy (vanatat.ru, plain
# HTTP) because vercel.app is blocked on part of RU networks — measure its
# home page too.
EXTRA = [("vanatat.ru:/", "http://vanatat.ru/")]

METRICS = {
    "LCP_ms": "largest-contentful-paint",
    "FCP_ms": "first-contentful-paint",
    "TBT_ms": "total-blocking-time",
    "CLS": "cumulative-layout-shift",
    "SI_ms": "speed-index",
    "TTI_ms": "interactive",
}


def run_once(target: str, ff: str, i: int, tag: str) -> dict:
    out = RAW / f"{tag}_{ff}_{i}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    cmd = [str(LH), target, "--output=json", f"--output-path={out}", "--quiet",
           "--chrome-flags=--headless=new --no-sandbox --disable-gpu",
           "--max-wait-for-load=60000"]
    if ff == "desktop":
        cmd.append("--preset=desktop")
    env = dict(os.environ, CHROME_PATH=CHROME)
    t0 = time.monotonic()
    p = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=600)
    if p.returncode != 0 or not out.exists():
        return {"error": (p.stderr or p.stdout)[-400:]}
    r = json.loads(out.read_text())
    a = r["audits"]
    res = {"wall_s": round(time.monotonic() - t0),
           "runtimeError": r.get("runtimeError", {}).get("code"),
           "scores": {k: round(v["score"] * 100) if v.get("score") is not None else None
                      for k, v in r["categories"].items()}}
    for name, aid in METRICS.items():
        v = a.get(aid, {}).get("numericValue")
        res[name] = round(v, 3 if name == "CLS" else 0) if v is not None else None
    res["total_bytes"] = a.get("total-byte-weight", {}).get("numericValue")
    items = a.get("network-requests", {}).get("details", {}).get("items", [])
    res["requests"] = len(items)
    res["top5"] = [{"url": it["url"][:140], "kb": round(it.get("transferSize", 0) / 1024), "type": it.get("resourceType")}
                   for it in sorted(items, key=lambda x: -x.get("transferSize", 0))[:5]]
    res["lcp_element"] = (a.get("largest-contentful-paint-element", {}).get("details", {}) or {})
    try:
        res["lcp_element"] = res["lcp_element"]["items"][0]["items"][0]["node"]["snippet"][:200]
    except Exception:  # noqa: BLE001
        res["lcp_element"] = None
    res["failed_audits"] = sorted(
        k for k, v in a.items()
        if v.get("score") is not None and v.get("score") < 0.9 and v.get("scoreDisplayMode") in ("binary", "numeric", "metricSavings"))
    return res


def main():
    results = {}
    targets = [(p, url(p)) for p in KEY_PAGES] + EXTRA
    for tag_path, target in targets:
        tag = tag_path.strip("/").replace("/", "_").replace(":", "") or "home"
        for ff in ("mobile", "desktop"):
            runs = []
            for i in range(RUNS):
                print(f"lighthouse {tag} {ff} run {i + 1}/{RUNS}", flush=True)
                runs.append(run_once(target, ff, i, tag))
            ok = [r for r in runs if "scores" in r]
            med = {}
            if ok:
                for cat in ok[0]["scores"]:
                    med[cat] = median([r["scores"].get(cat) for r in ok])
                for name in list(METRICS) + ["total_bytes", "requests"]:
                    med[name] = median([r.get(name) for r in ok])
            results[f"{tag_path} [{ff}]"] = {"url": target, "form_factor": ff, "runs_ok": len(ok),
                                            "median": med, "runs": runs}
            save_json("lighthouse.json", {
                "conditions": __doc__.split("Output:")[0].strip(),
                "runs_per_config": RUNS, "results": results})


if __name__ == "__main__":
    main()
